- .gitignore
- docs/index.md
- mkdocs.yml
fix mkdocs, edited gitignore to ignore docs/plugins/since these are generated.
> Sdkboxdocs 2

- docs/index.md
- mkdocs.yml
- src/adcolony/v3-cpp/usage.md
- src/adcolony/v3-js/usage.md
- src/chartboost/v3-cpp/usage.md
- src/chartboost/v3-js/usage.md
- src/flurryanalytics/v3-cpp/api-reference.md
- src/flurryanalytics/v3-cpp/usage.md
- src/flurryanalytics/v3-js/api-reference.md
- src/flurryanalytics/v3-js/usage.md
- src/flurryanalytics/v3-lua/api-reference.md
- src/googleanalytics/v3-cpp/usage.md
- src/googleanalytics/v3-js/usage.md
- src/iap/v3-cpp/usage.md
- src/iap/v3-js/usage.md
- src/kochava/v3-cpp/usage.md
- src/kochava/v3-js/usage.md
- src/tune/v3-cpp/usage.md
- src/tune/v3-js/usage.md
- src/vungle/v3-cpp/usage.md
- src/vungle/v3-js/usage.md
changed these to have the same updates as the PDF docs.
> Sdkboxdocs 4

- src/facebook/v2-lua/usage.md
- src/facebook/v3-cpp/usage.md
- src/facebook/v3-js/usage.md
- src/facebook/v3-lua/usage.md
fixed indent issue that was causing code blocks to format incorrectly.
> corrected indent in code blocks causing formatting issue

- src/facebook/v2-lua/usage.md
- src/facebook/v3-cpp/proguard.md
- src/facebook/v3-cpp/usage.md
- src/facebook/v3-js/usage.md
- src/facebook/v3-lua/usage.md
more Facebook adjustments, I still need help with verifying JS and Lua items, in terms of things like sharing a link, photo, etc.
> more Facebook adjustments

- src/facebook/readme.md
- src/facebook/v3-cpp/usage.md
- src/facebook/v3-js/usage.md
- src/facebook/v3-lua/usage.md
> minor edits to Facebook

- src/googleanalytics/v2-lua/usage.md
> corrected typo

- src/adcolony/shared/manual_android_v2.md
- src/adcolony/shared/manual_android_v3.md
- src/agecheq/shared/manual_android_v2.md
- src/agecheq/shared/manual_android_v3.md
- src/chartboost/shared/manual_android_v2.md
- src/chartboost/shared/manual_android_v3.md
- src/facebook/shared/manual_android_v2.md
- src/facebook/shared/manual_android_v3.md
- src/flurryanalytics/shared/manual_android_v2.md
- src/flurryanalytics/shared/manual_android_v3.md
- src/googleanalytics/shared/manual_android_v2.md
- src/googleanalytics/shared/manual_android_v3.md
- src/iap/shared/manual_android_v2.md
- src/iap/shared/manual_android_v3.md
- src/kochava/shared/manual_android_v2.md
- src/kochava/shared/manual_android_v3.md
- src/tune/shared/manual_android_v2.md
- src/tune/shared/manual_android_v3.md
- src/vungle/shared/manual_android_v2.md
- src/vungle/shared/manual_android_v3.md
replace LOCAL_STATIC_LIBRARIES with LOCAL_WHOLE_STATIC_LIBRARIES
> replace LOCAL_STATIC_LIBRARIES with LOCAL_WHOLE_STATIC_LIBRARIES

- src/vungle/v2-lua/usage.md
- src/vungle/v3-cpp/usage.md
- src/vungle/v3-js/usage.md
- src/vungle/v3-lua/usage.md
> add vungle notice

- docs/index.md
- mkdocs.yml
- src/fyber/v3-cpp/usage.md
- added Fyber to MkDocs
- added missing plugins to index.md
- stated to refine Fyber docs
> 2015 09 08 fixes

- src/adcolony/v3-js/usage.md
- src/agecheq/v3-js/usage.md
- src/chartboost/v3-js/usage.md
- src/facebook/v3-js/usage.md
- src/flurryanalytics/v3-js/usage.md
- src/tune/v3-js/usage.md
- src/vungle/v3-js/usage.md
Corrected JS callbacks to match what currently is the case. Will need to update again when changed.
> corrected discrepencies in JS register functions

- src/soomlagrow/shared/manual_ios_v3.md
changes to finalize Soomla docs
> updated to include required system frameworks

- src/fyber/v2-lua/usage.md
- src/fyber/v3-cpp/usage.md
- src/fyber/v3-js/usage.md
- src/fyber/v3-lua/usage.md
clarification of requestOffers() and showOffers()
> clarification of requestOffers() and showOffers()

- src/soomlagrow/readme.md
> updated JSON keys

- src/adcolony/shared/manual_android_v2.md
- src/agecheq/shared/manual_android_v2.md
- src/chartboost/shared/manual_android_v2.md
- src/facebook/shared/manual_android_v2.md
- src/flurryanalytics/shared/manual_android_v2.md
- src/fyber/shared/manual_android_v2.md
- src/googleanalytics/shared/manual_android_v2.md
- src/iap/shared/manual_android_v2.md
- src/kochava/shared/manual_android_v2.md
- src/review/shared/manual_android_v2.md
- src/soomlagrow/shared/manual_android_v2.md
- src/tune/shared/manual_android_v2.md
- src/vungle/shared/manual_android_v2.md
corrected Android heading for v2 after re-formatting changes.
> corrected Android heading for v2 after re-formatting changes.

- src/shared/notice.md
fixed a few typos and formatting items
> fixed a few typos and formatting items

- src/bee7/readme.md
minor placement modification and grammar fix
> minor placement modification and grammar fix

- src/soomlagrow/readme.md
- src/soomlagrow/shared/manual_ios_v3.md
- src/soomlagrow/v2-lua/usage.md
- src/soomlagrow/v3-cpp/usage.md
- src/soomlagrow/v3-js/usage.md
- src/soomlagrow/v3-lua/usage.md
corrected to SOOMLA Grow, fixed a few typos
> corrected to SOOMLA Grow, fixed a few typos

- docs/installer.md
> updated to latest version

- docs/release-note.md
- mkdocs.yml
- src/soomlagrow/readme.md
- Changed "Soomla" => "SOOMLA"
- Updated registration URL
> Url and name fixes

- src/adcolony/v3-cpp/api-reference.md
- src/facebook/v2-lua/usage.md
- src/facebook/v3-cpp/api-reference.md
- src/facebook/v3-cpp/usage.md
- src/facebook/v3-js/usage.md
- src/facebook/v3-lua/usage.md
> 2015 10 12

- src/soomlagrow/v2-lua/usage.md
> was missing

- src/facebook/readme.md
- src/facebook/v3-cpp/usage.md
- src/facebook/v3-js/usage.md
- src/facebook/v3-lua/usage.md
Fixed Facebook formatting error in invite section
> corrected invite section format error

- publish.sh
made this 1.3 instead of master
> made this 1.3 instead of master

- src/googleanalytics/shared/manual_android_v2.md
- src/googleanalytics/shared/manual_android_v3.md
added new manifest items, per Ibon
> added new manifest items, per Ibon

- src/facebook/readme.md
> clarified facebook version

- src/adcolony/readme.md
- src/fyber/readme.md
- src/soomlagrow/readme.md
added plugin compatability warning
> added plugin compatability warning

- src/appodeal/v3-cpp/api-reference.md
- src/appodeal/v3-js/api-reference.md
- src/appodeal/v3-lua/api-reference.md
> removed AdColony reference

- src/achievement/readme.md
- src/leaderboard/readme.md
- src/playphone/readme.md
1. update channel info for Google Play
2. add some prerequisites for Achievement and Leaderboard
> playphone update

- src/facebook/v3-cpp/usage.md
- src/facebook/v3-js/usage.md
- src/facebook/v3-lua/usage.md
added app_link_url clarification, per Ibon
> added app_link_url clarification, per Ibon

- src/achievement/v3-cpp/proguard.md
- src/adcolony/v3-cpp/proguard.md
- src/agecheq/v3-cpp/proguard.md
- src/appodeal/v3-cpp/proguard.md
- src/bee7/v3-cpp/proguard.md
- src/chartboost/v3-cpp/proguard.md
- src/facebook/v3-cpp/proguard.md
- src/flurryanalytics/v3-cpp/proguard.md
- src/fyber/v3-cpp/proguard.md
- src/googleanalytics/v3-cpp/proguard.md
@slackmoehrle 
add proguard setting for some plugins
> add proguard setting

- src/appodeal/readme.md
Appodeal conflicts with Flurry Analytics and Chartboost together.
> added appodeal conflict info

- .gitignore
- docs/plugins/appodeal/index.html
- docs/plugins/bee7/index.html
- docs/plugins/playphone/index.html
- docs/plugins/scientificrevenue/index.html
- docs/plugins/valuepotion/index.html
- docs/plugins/youtube/index.html
- docs/release-note.md
Add missing static webpages. These are used as direct links to docs from Programmers Guide.
> Add missing static webpages

- src/adcolony/shared/manual_ios_v3.md
- src/bee7/shared/manual_ios_v3.md
- src/fyber/shared/manual_ios_v3.md
> Fix manual ios

- src/playphone/readme.md
removed two playphone pre-requisites and added the second one as a note to the first one.
> removed duplicate playphone prerequisite

- src/fyber/v3-cpp/api-reference.md
- src/fyber/v3-js/api-reference.md
- src/fyber/v3-lua/api-reference.md
maybe merge this pr next release
> add fyber user segmentation documentation

- docs/unreal/iap/index.md
change url to "www.sdkbox.com/unreal"
> fix unreal iap download url.

- src/facebook/readme.md
- src/facebook/shared/manual_android_v3.md
> Facebook: update iOS simulator setting

- mkdocs.yml
> Phunware messaging

- docs/release-note.md
fix misspelling, markdown format
> Fix release note

- README.md
- publish.sh
> 1.  Add 'test' option to 'publish.sh'.

- src/gameroom/index.md
- src/gameroom/v3-cpp/usage.md
1. adjust the order of images in index.md
2. change from escape symbol "\n" to "\\n" in MarkDown.
> adjust the order of images in index.md
